config/routes.rb
AuthenticationServer::Application.routes.draw do
  namespace :api do
    get "request/callback"
    resources :request, :only => [:new, :create, :callback]
  end
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "logout" => "sessions#destroy"
  get "login" => "sessions#new"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "sessions#new"
  resources :users
  resources :sessions
  resources :app_details

end

app/models/app_detail.rb
class AppDetail < ActiveRecord::Base
  belongs_to :user
	before_create :generate_token

  def self.authenticate_app params
    if valid_url? params[:redirect_uri]
      begin
        details = where(client_id: params[:client_id], app_secret: params[:app_secret]).first 
        return details
      rescue Exception => e 
        return {status: false, reason: "Invalid App Details"}
      end
    else
      return {status: false, reason: "Invalid URI"}
    end
  end

	protected

  def generate_token
    self.app_secret = loop do
      random_code = SecureRandom.urlsafe_base64(nil, false)
      break random_code unless AppDetail.exists?(app_secret: random_code)
    end

    self.client_id = loop do
      random_id = SecureRandom.hex(12)
      break random_id unless AppDetail.exists?(client_id: random_id)
    end
  end

  def self.valid_url? url
    begin
      uri = URI.parse(url)
      return uri.kind_of?(URI::HTTP)
    rescue Exception => e
      return false
    end
    
  end

  def generate_temp_code
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :app_detail

  before_create :generate_tokens
  def generate_api_code

  end

  private
  
  def generate_tokens
    begin
      self.access_token = SecureRandom.hex(10)
    end while self.class.exists?(access_token: access_token)

    begin
      self.code = SecureRandom.hex(10)
    end while self.class.exists?(code: code)
  end
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  has_one :token
  has_many :app_details
	
  before_validation :prep_email

  has_secure_password

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  validates :password_digest, presence: true


  def self.authenticate_user params
    user = where(email: params[:email]).first rescue nil
    if user && user.authenticate(params[:password])
      return user
    else
      return false
    end
  end

  private

  def prep_email
    self.email = self.email.strip.downcase if self.email
  end

end

app/controllers/api/request_controller.rb
class Api::RequestController < ApplicationController
  
  def new
  	@authenticate = AppDetail.authenticate_app(params)
    if @authenticate.is_a?(Hash)
      render json: @authenticate
    else
  	 @redirect_uri = params[:redirect_uri]
  	end
  end

  def create
    user = User.authenticate_user params
    if user
      token = if user.token.blank?
                Token.create(user_id: user.id) 
              else
                user.token
              end
      url = params[:redirect_uri]
      url += "?" unless params[:redirect_uri].include?("?")
      url +=  {code: token.code}.to_param
      redirect_to url
    else
      render 'new', :redirect_uri => params[:redirect_uri]
    end

  end

  def callback
    response = begin
      token = Token.where(code: params[:code]).first
          {status: true, access_token: token.access_token}
        rescue Exception => e
          {status: false, reason: "Invalid Request"}
        end
    render json: response
  end

end

app/controllers/app_details_controller.rb
class AppDetailsController < ApplicationController
  before_action :login_required
  before_action :set_app_detail, only: [:show, :edit, :update, :destroy]

  # GET /app_details
  # GET /app_details.json
  def index
    @app_details = AppDetail.all
  end

  # GET /app_details/1
  # GET /app_details/1.json
  def show
  end

  # GET /app_details/new
  def new
    @app_detail = AppDetail.new
  end

  # GET /app_details/1/edit
  def edit
  end

  # POST /app_details
  # POST /app_details.json
  def create

    @app_detail = AppDetail.new(app_detail_params.merge(user_id: session[:user_id]))

    respond_to do |format|
      if @app_detail.save
        format.html { redirect_to @app_detail, notice: 'App detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @app_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @app_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_details/1
  # PATCH/PUT /app_details/1.json
  def update
    respond_to do |format|
      if @app_detail.update(app_detail_params)
        format.html { redirect_to @app_detail, notice: 'App detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_details/1
  # DELETE /app_details/1.json
  def destroy
    @app_detail.destroy
    respond_to do |format|
      format.html { redirect_to app_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_detail
      @app_detail = AppDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_detail_params
      params.require(:app_detail).permit(:name, :redirect_url, :client_id, :secret_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  add_flash_types :error, :success

	private

	def current_user
  	session[:user_id]
	end


  def session_expiry
    expire_time = session[:expires_at] || Time.current
    @time_left = (expire_time - Time.current).to_i
    unless @time_left > 0
      reset_session
      flash[:error] = 'Please login to continue'
    end
  end


  def login_required
    if session[:user_id]
       # set current user object to @current_user object variable
      @current_user = current_user
      return true
    else
      redirect_to login_path, error:"Please login to continue"
      return false
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'
  def new
    if current_user
      redirect_to app_details_path and return 
    end
  end

  def create
      user = User.authenticate_user params
    if user
      session[:user_id] = user.id
      redirect_to app_details_path, success: "Logged in!"
    else
      redirect_to root_url, error: "Invalid Email/Password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'login'
  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thank you for signing up!!!"
    else
      redirect_to app_details_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/api/request_helper.rb
module Api::RequestHelper
end

app/helpers/app_details_helper.rb
module AppDetailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app_details/_form.html.erb
<%= form_for(@app_detail) do |f| %>
  <% if @app_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_detail.errors.count, "error") %> prohibited this app_detail from being saved:</h2>

      <ul>
      <% @app_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :redirect_url %><br>
    <%= f.text_area :redirect_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_details/edit.html.erb
<h1>Editing app_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_detail %> |
<%= link_to 'Back', app_details_path %>

app/views/app_details/index.html.erb
<h1>Listing app_details</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Redirect url</th>
      <th>Client</th>
      <th>Secret code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @app_details.each do |app_detail| %>
      <tr>
        <td><%= app_detail.name %></td>
        <td><%= app_detail.redirect_url %></td>
        <td><%= app_detail.client_id %></td>
        <td><%= app_detail.app_secret %></td>
        <td><%= link_to 'Show', app_detail %></td>
        <td><%= link_to 'Destroy', app_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App detail', new_app_detail_path %>

app/views/app_details/new.html.erb
<h1>Register a New App</h1>

<%= render 'form' %>

<%= link_to 'Back', app_details_path %>

app/views/app_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app_detail.name %>
</p>

<p>
  <strong>Redirect url:</strong>
  <%= @app_detail.redirect_url %>
</p>

<p>
  <strong>Client:</strong>
  <%= @app_detail.client_id %>
</p>

<p>
  <strong>App code:</strong>
  <%= @app_detail.app_secret %>
</p>

<%= link_to 'Back', app_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AuthenticationServer" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">AuthenticationServer</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Apps", app_details_path  %></li>
              <li><%= link_to "Logout", logout_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AuthenticationServer" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">AuthenticationServer</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Sign Up", sign_up_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name , placeholder: "name"%>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email, placeholder: "email" %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password, placeholder: "password" %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>